import PDFDocument from 'pdfkit';
import * as fs from 'fs';
import * as path from 'path';

export interface ReportData {
  balance?: number;
  positions: Array<{
    ticker: string;
    side: string;
    position: number;
    cost: number;
    payout?: number;
    pnl: number;
    gameInfo?: string;
  }>;
  games: Array<{
    sport: string;
    gameId: string;
    awayTeam: string;
    homeTeam: string;
    scheduledTime: string;
    status: string;
    sides: Array<{
      team: string;
      side: string;
      kalshiPrice: number;
      kalshiProb: number;
      espnOdds: number;
      espnProb: number;
      diffPct: number;
      isOverThreshold: boolean;
      isKalshiOvervaluing: boolean;
      hasPosition?: boolean;
      positionCount?: number;
      positionSide?: string;
      positionPayout?: number;
    }>;
  }>;
}

export class PDFService {
  /**
   * Generate PDF report from report data
   */
  async generatePDF(reportData: ReportData): Promise<string> {
    const doc = new PDFDocument({ margin: 50 });
    const fileName = `mispricing-report-${new Date().toISOString().split('T')[0]}-${Date.now()}.pdf`;
    const filePath = path.join(__dirname, '..', '..', 'reports', fileName);
    
    // Ensure reports directory exists
    const reportsDir = path.dirname(filePath);
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }
    
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);
    
    // Header
    doc.fontSize(20).text('Mispricing Report', { align: 'center' });
    doc.fontSize(12).text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
    doc.moveDown(2);
    
    // Account Balance
    if (reportData.balance !== undefined) {
      doc.fontSize(16).text('Account Balance', { underline: true });
      doc.fontSize(14).text(`$${reportData.balance.toFixed(2)}`, { indent: 20 });
      doc.moveDown();
    }
    
    // Active Positions
    if (reportData.positions.length > 0) {
      doc.fontSize(16).text('Active Positions', { underline: true });
      doc.moveDown(0.5);
      
      reportData.positions.forEach((pos, idx) => {
        doc.fontSize(12).text(`${idx + 1}. ${pos.gameInfo || pos.ticker}`, { indent: 20 });
        doc.fontSize(10).text(`   Side: ${pos.side} | Position: ${pos.position} | Cost: $${pos.cost.toFixed(2)}`, { indent: 20 });
        if (pos.payout) {
          doc.text(`   Payout: $${pos.payout.toFixed(2)}`, { indent: 20 });
        }
        doc.text(`   P&L: $${pos.pnl.toFixed(2)}`, { indent: 20 });
        doc.moveDown(0.5);
      });
      doc.moveDown();
    }
    
    // Games and Mispricings
    if (reportData.games.length > 0) {
      doc.fontSize(16).text('Games & Mispricings', { underline: true });
      doc.moveDown(0.5);
      
      reportData.games.forEach((game, gameIdx) => {
        doc.fontSize(14).text(`${gameIdx + 1}. ${game.awayTeam} @ ${game.homeTeam}`, { indent: 20 });
        doc.fontSize(10).text(`   Game ID: ${game.gameId}`, { indent: 20 });
        doc.text(`   Scheduled: ${new Date(game.scheduledTime).toLocaleString()}`, { indent: 20 });
        doc.text(`   Status: ${game.status}`, { indent: 20 });
        doc.moveDown(0.5);
        
        game.sides.forEach((side) => {
          doc.fontSize(12).text(`   ${side.team} (${side.side})`, { indent: 30 });
          doc.fontSize(10).text(`      Kalshi: ${side.kalshiPrice} → ${(side.kalshiProb * 100).toFixed(2)}%`, { indent: 30 });
          doc.text(`      ESPN: ${side.espnOdds > 0 ? '+' : ''}${side.espnOdds} → ${(side.espnProb * 100).toFixed(2)}%`, { indent: 30 });
          doc.text(`      Difference: ${side.diffPct.toFixed(2)} percentage points`, { indent: 30 });
          
          if (side.isOverThreshold) {
            doc.text(`      ⚠️ ABOVE THRESHOLD`, { indent: 30 });
            if (side.isKalshiOvervaluing) {
              doc.text(`      💰 OPPORTUNITY: Kalshi overvalues ${side.team} - bet against on Kalshi`, { indent: 30 });
            } else {
              doc.text(`      💰 OPPORTUNITY: Kalshi undervalues ${side.team} - bet on Kalshi`, { indent: 30 });
            }
          } else {
            doc.text(`      Below threshold`, { indent: 30 });
          }
          
          if (side.hasPosition) {
            doc.text(`      Active Position: ${side.positionCount} ${side.positionSide}`, { indent: 30 });
            if (side.positionPayout) {
              doc.text(`      Payout: $${side.positionPayout.toFixed(2)}`, { indent: 30 });
            }
          }
          
          doc.moveDown(0.5);
        });
        
        doc.moveDown();
      });
    }
    
    // Footer
    doc.fontSize(10).text(
      `Report generated by Kalshi Mispricing Bot`,
      { align: 'center' }
    );
    
    doc.end();
    
    return new Promise((resolve, reject) => {
      stream.on('finish', () => resolve(filePath));
      stream.on('error', reject);
    });
  }
}

